import type { Metadata } from "next";
import "./globals.css";
import HeroUiProvider from "./providers/heroProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeroUiProvider>
          {children}
        </HeroUiProvider>
      </body>
    </html>
  );
}
